sonar.projectKey=javedfgiet_Learning-GitHub-Actions
sonar.organization=javedfgiet


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Learning-GitHub-Actions
sonar.projectVersion=1.0

#Coverage report path
sonar.python.coverage.reportPaths=reports/coverage.xml

#Unit Test report path
sonar.python.xunit.reportPath=reports/test-reports.xml

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8