name: CI pipeline
on: 
  workflow_dispatch:
  push: 
   branches:
     - main
  pull_request:
    branches:
      - main

jobs:
  ci-pipeline-job:
    uses: javedfgiet/reusable-workflows/.github/workflows/ci-pipeline.yaml@main
    secrets:
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}



  
      
